/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContactsIndexImport } from './routes/contacts/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ContactsContactIdLazyImport = createFileRoute('/contacts/$contactId')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ContactsIndexRoute = ContactsIndexImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacts/index.lazy').then((d) => d.Route),
)

const ContactsContactIdLazyRoute = ContactsContactIdLazyImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacts/$contactId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/contacts/$contactId': typeof ContactsContactIdLazyRoute
  '/contacts': typeof ContactsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/contacts/$contactId': typeof ContactsContactIdLazyRoute
  '/contacts': typeof ContactsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/contacts/$contactId': typeof ContactsContactIdLazyRoute
  '/contacts/': typeof ContactsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacts/$contactId' | '/contacts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacts/$contactId' | '/contacts'
  id: '__root__' | '/' | '/contacts/$contactId' | '/contacts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ContactsContactIdLazyRoute: typeof ContactsContactIdLazyRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ContactsContactIdLazyRoute: ContactsContactIdLazyRoute,
  ContactsIndexRoute: ContactsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contacts/$contactId",
        "/contacts/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/contacts/$contactId": {
      "filePath": "contacts/$contactId.lazy.tsx"
    },
    "/contacts/": {
      "filePath": "contacts/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
